import { Response } from 'express'

import jwt from 'jsonwebtoken'

import { JWT_SIGNER_SECRET, cookieOptions } from '../config'

import { SessionValues } from '../utils/types'

/**
 * Saves the session values as a JSON-Web-Token on a Cookie of the browser, called 'sessionJWT'.
 */
export function setSessionCookie(payload: SessionValues, response: Response) {
  // Create a Json-Web-Token:
  // set the expiration of JWT same as the Cookie
  const jwtOptions = {
    expiresIn: `${cookieOptions.maxAge} seconds`
  }
  const token = jwt.sign(payload, JWT_SIGNER_SECRET, jwtOptions)

  // Set a Cookie in the header including the JWT and our options:

  response.cookie('sessionJWT', token, cookieOptions)

  console.log(
    "The JSON-Web-Token with Session Values generated by the backend was saved on the 'sessionJWT'-Cookie. \n"
  )
}
